---
version: "2"
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /disk-to-path//Configs/hassio:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    ports:
      - 8123:8123
## Media Server
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=998
      - PGID=100
      - TZ=Europe/London
      - JELLYFIN_PublishedServerUrl=192.168.100.4
    volumes:
      - /disk-to-path//Config/Jellyfin:/config
      - /disk-to-path//Series:/Series
      - /disk-to-path//Movies:/Movies
      - /disk-to-path//Documentary:/Documentary
      - /disk-to-path//Cartoons:/Cartoons
      - /dev/shm:/transcode:rw
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
    devices:
      # VAAPI Devices (examples)
  #   - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
## Surveillance 
  motioneye:
    image: ccrisan/motioneye:master-armhf
    container_name: motioneye
    restart: unless-stopped
    volumes:
      - /disk-to-path//Configs/motioneye/etc:/etc/motioneye
      - /disk-to-path//Downloads/motioneye/lib:/var/lib/motioneye
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8765:8765"
    devices:
     # - /dev/video0:/dev/video0
	  #   - /dev/dri/card0:/dev/dri/card0